name: Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Release level'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-24.04

    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4 # v1.11.0

      - name: Install cargo-release
        uses: taiki-e/install-action@067268f3aa4f1f3c2becf69d7454955cfab17334 # v2.50.1
        with:
          tool: cargo-release

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run cargo release
        run: cargo release ${{ github.event.inputs.level }} --execute --no-confirm

      - name: Get the latest tag
        id: tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Create a release
        run: gh release create ${{ steps.tag.outputs.tag }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  build:
    needs: release

    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.platform.runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4 # v1.11.0

      - name: Build
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Rename binary
        run: mv target/${{ matrix.platform.target }}/release/pacx ./pacx_${{ needs.release.outputs.tag }}_${{ matrix.platform.target }}

      - name: Upload build artifact
        run: gh release upload ${{ needs.release.outputs.tag }} ./pacx_${{ needs.release.outputs.tag }}_${{ matrix.platform.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
